[placeholders.board]
type = "string"
prompt = "Which board do you use?"
choices = [
  "Adafruit Trinket",
  "Adafruit Trinket Pro",
  "Arduino Leonardo",
  "Arduino Mega 2560",
  "Arduino Nano",
  "Arduino Nano New Bootloader",
  "Arduino Uno",
  "SparkFun ProMicro",
  "Nano168",
  "Digispark + Micronucleus"
]
default = "Arduino Uno"
